### ISSUE TITLE
Adapter crashes continuous

### ISSUE THREAD

**Issue by rvdgaag** [ioBroker/ioBroker.digitalstrom#98]
The adapter crashed and restarts over an over again.

 - Adapter version: 2.2.0
 - JS-Controller version: 3.3.14
 - Node version: 12.22.3
 - Operating system: dSS 1.19.0
 
Here is a part of the log-file:

2021-07-23 15:48:52.081 - info: digitalstrom.0 (2327) 6 Output values for device a25c215a2c845425c056019a3c16936400 are unsupported
--
2021-07-23 15:48:52.081 - warn: digitalstrom.0 (2327) INVALID OUTPUTCHANNEL TYPE videoStation: {"channelId":"videoStation","channelType":"videoStation","channelIndex":2,"channelName":"video station"}
2021-07-23 15:48:52.081 - warn: digitalstrom.0 (2327) INVALID OUTPUTCHANNEL TYPE videoInputSource: {"channelId":"videoInputSource","channelType":"videoInputSource","channelIndex":3,"channelName":"video input source"}
2021-07-23 15:48:52.083 - info: digitalstrom.0 (2327) 4 Output values for device 8b43dc23eff75a49c0107baa140a523d00 are unsupported
2021-07-23 15:49:22.146 - error: digitalstrom.0 (2327) uncaught exception: Unexpected token u in JSON at position 0
2021-07-23 15:49:22.147 - error: digitalstrom.0 (2327) SyntaxError: Unexpected token u in JSON at position 0
at JSON.parse ()
at DSSStructure.addStateObject (/opt/iobroker/node_modules/iobroker.digitalstrom/lib/dssStructure.js:1612:24)
at /opt/iobroker/node_modules/iobroker.digitalstrom/lib/dssStructure.js:1056:22
at Array.forEach ()
at DSSStructure.createApartment (/opt/iobroker/node_modules/iobroker.digitalstrom/lib/dssStructure.js:1044:23)
at /opt/iobroker/node_modules/iobroker.digitalstrom/lib/dssStructure.js:151:18
at /opt/iobroker/node_modules/iobroker.digitalstrom/lib/dssStructure.js:265:49
at Immediate. (/opt/iobroker/node_modules/iobroker.digitalstrom/lib/dssStructure.js:791:40)
at processImmediate (internal/timers.js:461:21)
2021-07-23 15:49:22.147 - error: digitalstrom.0 (2327) Unexpected token u in JSON at position 0
2021-07-23 15:49:22.148 - warn: digitalstrom.0 (2327) Exception: SyntaxError: Unexpected token u in JSON at position 0
2021-07-23 15:49:22.148 - info: digitalstrom.0 (2327) stopping ... 1627048162148
2021-07-23 15:49:22.148 - info: digitalstrom.0 (2327) cleaned everything up... 0
2021-07-23 15:49:23.192 - warn: digitalstrom.0 (2327) Terminated (UNCAUGHT_EXCEPTION): Without reason
2021-07-23 15:49:23.724 - error: host.iobrokeri7 instance system.adapter.digitalstrom.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2021-07-23 15:49:23.726 - info: host.iobrokeri7 Restart adapter system.adapter.digitalstrom.0 because enabled

**Comment by Apollon77** [comment]
Ok, it seems that your installation have a new appartment state which is unknown. I added a check for that. Please try GitHub version. YOu need to manually restart adapter after install. Version stays 2.2.0 for now.
YOu should now find a new logile "INVALID appartment state ..." ... would be interesting to get that (or also in genral the "INVALID" ones :-)

**Comment by rvdgaag** [comment]
I reinstalled the GitHub version and it works fine now.

Where can I find the new logfile ??

**Comment by Apollon77** [comment]
Logfile is on /opt/iobroker/log/...

**Comment by rvdgaag** [comment]
Here it is
[iobroker.2021-07-26.log](https://github.com/ioBroker/ioBroker.digitalstrom/files/6876064/iobroker.2021-07-26.log)

**Comment by rvdgaag** [comment]
I believe the INVALID comes from new functionality, the dam units also report now power production, not only power consumption.

**Comment by Apollon77** [comment]
Can you please do thelog again and enable debug lohging before it? Debug log is: Instance s- expert mdoe and then change loglevel for the instance to debug

**Comment by rvdgaag** [comment]
Here you are
[iobroker.2021-07-26.log](https://github.com/ioBroker/ioBroker.digitalstrom/files/6878363/iobroker.2021-07-26.log)

**Comment by Apollon77** [comment]
Ok, I can not find any documenttion for these new apartment fields apartment-power-production-on2500-off500, apartment-power-production-on3500-off2600, apartment-power-production-on4000-off3600, apartment-power-production-on5000-off4000 ... So I would leave them out for now ... or are ahaveing any infos? Was anything in changelogs?

Other than that I also saw datatype info messages ... i fixed them.

**Comment by rvdgaag** [comment]
These power production states are user defined states as listed in the API

**Comment by Apollon77** [comment]
Yes bit I did not expetced them to be in the "normal propeties" (because4 they are not in user properties).

In fact the adapter assumes all properties with a "." in the name to be apartmental properties with defined names :-)
Basically this means the adapter do not know anything about these fields beside the name and the current value (2/inactive as example). But no idea about other possible values. Or can I assume it always is "actove/inactive" only?? If yes I could add parsing of it

**Comment by rvdgaag** [comment]
Yes these are always active/inactive values

**Comment by Apollon77** [comment]
Try GitHub version ... states hould be there now
